// <auto-generated />
namespace AutomotiveShop.model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MisspellingFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MisspellingFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201711051316317_MisspellingFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
